### PR TITLE
Added place properties

### PR DESCRIPTION
**Pull request by evgeny-petukhov**
#25

Caniuse issue: https://github.com/Fyrd/caniuse/issues/4094

### CODE REVIEW

**Comment by jonathantneal** [comment]
@evgeny-petukhov, I’m so impressed with this commit. It’s like you understood things about this project I never knew I communicated. Thank you so much!

I updated the title and description very slightly, and then I sorted it so all of the features are sorted by the `id` alphabetically. If you’re okay with my minor changes, then I will merge.

**Comment by jonathantneal** [comment]
Related: I will add `npm test` to the travis.yml. Had I done that, you would have caught this without my help.

**Comment by evgeny-petukhov** [comment]
Thank you for quick reaction (and also helping me with English 😀 )!

**Comment by evgeny-petukhov** [comment]
I can help you with enhancing the project. What about cli tool to add new features?

**Pull request merged**
